targets:
  - name: ddaodan-i18n
    sources:
      - /assets/**/
    file: /%original_path%/%locale%.json
    format: android
files:
  - source: /assets/**/
    translation: /%original_path%/%locale%.json
