targets:
  - name: ddaodan-i18n
    sources:
      - /assets/**/
    file: /%original_path%/%locale%.json
    format: android
files:
  - source: /assets/**/lang/en_us.json
    translation: /%original_path%/%language%.json
